# <span style="color: #FF00FF;">Nivell 1</span>

Des d'un Jupyter Notebook faràs els següents exercicis utilitzant la llibreria `requests` de Python.
Exploració bàsica amb una API de laboratori.

* 1. Consulta l'API pública [JSONPlaceholder](https://jsonplaceholder.typicode.com/) utilitzant el mètode GET per obtenir:
   * Llista de publicacions (`/posts`)
   * Llista d'usuaris (`/users`)
   * Llista de tasques (`/todos`)

* 2. Mostra per pantalla:
   * La quantitat total de cada recurs.
   * El codi d'estat de cada petició.

In [2]:
import requests
import pandas as pd

In [3]:
BASE = 'https://jsonplaceholder.typicode.com'
recursos = ['posts', 'users', 'todos']

for recurs in recursos:
    r = requests.get(f'{BASE}/{recurs}')
    dades = r.json()
    print(f'/{recurs} → codi: {r.status_code} | total: {len(dades)}')

/posts → codi: 200 | total: 100
/users → codi: 200 | total: 10
/todos → codi: 200 | total: 200

* 3. Fes una petició a una publicació inexistent per obtenir un error 404 i mostra el codi d'estat rebut.

In [4]:
r = requests.get(f'{BASE}/posts/9999')
print(f'Codi d\'estat: {r.status_code}')
print(f'Resposta: {r.json()}')

Codi d'estat: 404
Resposta: {}

* 4. Fes una petició POST per crear una nova publicació fictícia. Inclou el títol, el cos del missatge i un userId.
   * Mostra la resposta JSON.
   * Mostra el codi d'estat.

In [5]:
nova_publicacio = {
    'title': 'IT Academy - Barcelona Activa',
    'body': "Aquest és l'últim sprint del bootcamp",
    'userId': 1
}

r = requests.post(f'{BASE}/posts', json=nova_publicacio)
print(f'Codi d\'estat: {r.status_code}')
print(f'Resposta JSON: {r.json()}')

Codi d'estat: 201
Resposta JSON: {'title': 'IT Academy - Barcelona Activa', 'body': "Aquest és l'últim sprint del bootcamp", 'userId': 1, 'id': 101}

* 5. Fes una petició PATCH per modificar parcialment una publicació existent.
   * Mostra la resposta JSON.
   * Mostra el codi d'estat.

<span style="color: #0099FF;">Visualitzem el post 1, per saber que volem canviar</span>

In [6]:
r = requests.get(f'{BASE}/posts/1')
print(r.json())

{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

<span style="color: #0099FF;">Canviem el títol</span>

In [7]:
canvis = {
    'title': 'Títol actualitzat amb PATCH'
}

r = requests.patch(f'{BASE}/posts/1', json=canvis)
print(f'Codi d\'estat: {r.status_code}')
print(f'Resposta JSON: {r.json()}')

Codi d'estat: 200
Resposta JSON: {'userId': 1, 'id': 1, 'title': 'Títol actualitzat amb PATCH', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

* 6. Fes una petició DELETE sobre una publicació.
   * Mostra la resposta JSON.
   * Mostra el codi d'estat.

In [8]:
r = requests.delete(f'{BASE}/posts/1')
print(f'Codi d\'estat: {r.status_code}')
print(f'Resposta JSON: {r.json()}')

Codi d'estat: 200
Resposta JSON: {}

# <span style="color: #FF00FF;">Nivell 2</span>

Interacció amb una [API pública real](https://github.com/public-apis/public-apis)

* 1. Explora el repositori de Public APIs i tria una API que permeti fer peticions GET.

* 2. Llegeix la documentació de l'API:
   * Revisa la secció d'endpoints disponibles. En un markdown, apunta com a mínim dos endpoints diferents.
   * Comprova si ofereix filtres o paràmetres opcionals interessants. En un markdown, anota'ls.
   * Verifica que la resposta sigui en format JSON (és el més adequat per a aquest exercici).

---

## API: Cat Facts
Documentació: https://catfact.ninja

### Endpoints disponibles
| Endpoint | Descripció |
|---|---|
| `GET /facts` | Retorna una llista de curiositats sobre gats |
| `GET /breeds` | Retorna una llista de races de gats |

### Paràmetres opcionals
- `/facts?limit=10` → retorna només 10 curiositats
- `/facts?max_length=100` → curiositats de màxim 100 caràcters
- `/breeds?limit=5` → retorna només 5 races

### Format de resposta
JSON

---

* 3. Fes una petició GET senzilla:
   * Mostra el codi d'estat de la resposta.
   * Imprimeix de forma clara alguns dels camps de la resposta JSON.

In [9]:
r = requests.get('https://catfact.ninja/facts?limit=10')
print(f'Codi d\'estat: {r.status_code}')

dades = r.json()
facts = dades['data']

print(f'\nTotal de random facts: {len(facts)}')
print('\nAlguns exemples:')
for f in facts[:3]:
    print(f'  - {f["fact"]} ({f["length"]} caràcters)')

Codi d'estat: 200

Total de random facts: 10

Alguns exemples:
  - Unlike dogs, cats do not have a sweet tooth. Scientists believe this is due to a mutation in a key taste receptor. (114 caràcters)
  - When a cat chases its prey, it keeps its head level. Dogs and humans bob their heads up and down. (97 caràcters)
  - The technical term for a cat’s hairball is a “bezoar.” (54 caràcters)

* 4. Converteix les dades a un DataFrame de pandas:
   * Mostra les primeres files del DataFrame.

In [10]:
pd.set_option('display.max_colwidth', None)
df_facts = pd.DataFrame(facts)
df_facts.head(10)

,fact,length
0,"Unlike dogs, cats do not have a sweet tooth. Scientists believe this is due to a mutation in a key taste receptor.",114
1,"When a cat chases its prey, it keeps its head level. Dogs and humans bob their heads up and down.",97
2,The technical term for a cat’s hairball is a “bezoar.”,54
3,A group of cats is called a “clowder.”,38
4,"A cat can’t climb head first down a tree because every claw on a cat’s paw points the same way. To get down from a tree, a cat must back down.",142
5,Cats make about 100 different sounds. Dogs make only about 10.,62
6,"Every year, nearly four million cats are eaten in Asia.",55
7,"There are more than 500 million domestic cats in the world, with approximately 40 recognized breeds.",100
8,Approximately 24 cat skins can make a coat.,43
9,"While it is commonly thought that the ancient Egyptians were the first to domesticate cats, the oldest known pet cat was recently found in a 9,500-year-old grave on the Mediterranean island of Cyprus. This grave predates early Egyptian art depicting cats by 4,000 years or more.",278

# <span style="color: #FF00FF;">Nivell 3</span>

API d'[Open Data Barcelona](https://opendata-ajuntament.barcelona.cat/ca/desenvolupadors#APIS)

* 1. Utilitza l'API d'Open Data BCN per:
   * Cercar un dataset del teu interès mitjançant `package_search` i `package_show`.

* 2. Dels resultats obtinguts, selecciona'n un que tingui recursos disponibles en CSV o JSON.

In [11]:
BASE_BCN = 'https://opendata-ajuntament.barcelona.cat/data/api/action'

r = requests.get(f'{BASE_BCN}/package_search', params={'q': 'medi ambient', 'rows': 10})
print(f'Codi d\'estat: {r.status_code}')

resultats = r.json()['result']['results']
for ds in resultats:
    print(f'  - {ds["name"]} → {ds["title"]}')

Codi d'estat: 200
  - rasters-mapa-estrategic-soroll → Raster noise maps from Strategic Noise Map of the city of Barcelona
  - piezometres_equipaments → List of piezometers and wells of the city of Bareclona
  - piezometres_detall → Detail of the measurements of the piezometers and wells of the city of Barcelona
  - atles-biodiversitat-arbrat-rel-geometria-especie → Geometry-species relationship of the trees of the Biodiversity Atlas of the city of Barcelona
  - atles-biodiversitat-flora-especies → Inventory of flora species of the Atlas of Biodiversity of the city of Barcelona city of Barcelona
  - atles-biodiversitat-flora-geometries → Inventory of flora geometries of the Atlas of Biodiversity of the city of Barcelona
  - atles-biodiversitat-flora-rel-geometria-especie → Geometry-species relationship of the flora of the Atlas of the Biodiversity of the city of Barcelona
  - atles-biodiversitat-arbrat-geometries → Inventory of tree geometries of the Biodiversity Atlas of the city of Barcelona
  - atles-biodiversitat-arbrat-especies → Inventory of tree species of the Atlas of Biodiversity of the city of Barcelona
  - facanes-mapa-estrategic-soroll → Noise maps by facade from Strategic Noise Map of the city of Barcelona

<span style="color: #0099FF;">Comprovem si el dataset té recursos CSV o JASON </span>

In [12]:
r = requests.get(f'{BASE_BCN}/package_show', params={'id': 'atles-biodiversitat-arbrat-especies'})
detalls = r.json()['result']

for rec in detalls['resources']:
    print(f'  - {rec["name"]} | format: {rec["format"]} | datastore_active: {rec["datastore_active"]}')

  - ab_vw_arbrat_especies.csv | format: CSV | datastore_active: True
  - ab_vw_arbrat_especies.json | format: JSON | datastore_active: False

<span style="color: #0099FF;">Busquem l'id del recurs que volem descarregar </span>

In [13]:
for rec in detalls['resources']:
    if rec['datastore_active']:
        print(f'resource_id: {rec["id"]}')

resource_id: c654c488-2822-4e51-ad9b-f443989a4b41

* 3. Amb el `resource_id` del recurs seleccionat, realitza una consulta mitjançant `datastore_search` per:
   * Recuperar almenys 100 registres.

In [14]:
r = requests.get(f'{BASE_BCN}/datastore_search', params={
    'resource_id': 'c654c488-2822-4e51-ad9b-f443989a4b41',
    'limit': 100
})
print(f'Codi d\'estat: {r.status_code}')

dades = r.json()['result']
print(f'Registres obtinguts: {len(dades["records"])}')
print(f'Total disponible: {dades["total"]}')

Codi d'estat: 200
Registres obtinguts: 100
Total disponible: 525

* 4. Converteix els resultats a un DataFrame.

In [15]:
df_arbres = pd.DataFrame(dades['records'])
print(f'Shape: {df_arbres.shape}')
df_arbres.head()

Shape: (100, 9)

,especie_id,nom_ctf,desc_eng,nom_eng,desc_cat,desc_cas,nom_cat,_id,nom_cas
0,158,Populus tremula,"This is a deciduous tree with a round crown. It is native to Europe, Central and Western Asia and North Africa. The leaf petiole is flat, elongated and flexible, which means that the leaves tremble in even slight breezes. It blossoms in February and March, with small catkins; the male reddish-grey flowers are woolly and the female flowers are green. It produces brown ovoid capsules that ripen between April and May and disseminate seeds covered in white cottony fibres. In Barcelona, it is planted in streets and squares, as well as in parks and gardens. The 'Pendula' cultivar can also be found.",Aspen,"Arbre caducifoli, de capçada arrodonida, originari d'Europa, del centre i l'oest d'Àsia i el nord d'Àfrica. El pecíol de les fulles és pla, allargat i flexible, per la qual cosa les fulles tremolen amb el ventijol més lleuger. La floració es produeix als mesos de febrer i març, amb flors menudes agrupades, les masculines llanoses i de color gris vermellós, i les femenines de color verd. Els fruits són càpsules ovoides marronoses que maduren entre l'abril i el maig i que disseminen unes llavors envoltades de pèls cotonosos blancs. A Barcelona s'utilitza com a arbrat viari, en places, i en parcs i jardins. Es pot trobar plantada la cultivar 'Pendula'.","Árbol caducifolio, de copa redondeada, originario de Europa, del centro y el oeste de Asia y el norte de África. El peciolo de las hojas es plano, alargado y flexible, por lo que las hojas tiemblan con la brisa más ligera. La floración se produce en los meses de febrero y marzo, con flores pequeñas agrupadas; las masculinas, lanosas y de color gris rojizo, y las femeninas, de color verde. Los frutos son cápsulas ovoides amarronadas que maduran entre abril y mayo y que diseminan unas semillas rodeadas de pelos algodonosos blancos. En Barcelona se utiliza como arbolado viario, en plazas y en parques y jardines. Se puede encontrar plantado el cultivar 'Pendula'.","Trémol, trèmol",1,"Alamo temblón, álamo temblón"
1,2437,Laurus nobilis 'Crispa',"An evergreen shrub or small tree with an ovoid crown, native to the Mediterranean region. It has aromatic leaves. It blossoms between February and April, with small greenish-yellow flowers. It produces black ovoid fruit that ripen in the autumn. In Barcelona, it is planted in parks and gardens and as a street tree. You can come across the 'Crispa' cultivar, which has undulating leaf margins. Its flowers attract pollinators and its fruit may attract some species of fauna.",Sweet bay,"Arbret o arbust perennifoli, de capçada ovoïdal, originari de la regió mediterrània. Les fulles són aromàtiques. Floreix entre els mesos de febrer i abril, amb flors petites i de color groc verdós. Els fruits són ovoides, de color negre, i maduren a la tardor. A Barcelona es planta en parcs i jardins i com a arbre viari. Podem trobar la cultivar 'Crispa', que presenta les fulles amb marge ondulat. La seva floració atrau pol·linitzadors i els seus fruits poden atraure algunes espècies de fauna.","Arbolillo o arbusto perennifolio, de copa ovoide, originario de la región mediterránea. Las hojas son aromáticas. Florece entre los meses de febrero y abril, con flores pequeñas y de color amarillo verdoso. Los frutos son ovoides, de color negro, y maduran en otoño. En Barcelona se planta en parques y jardines y como árbol viario. Podemos encontrar el cultivar 'Crispa', que presenta las hojas con borde ondulado. Su floración atrae polinizadores y sus frutos pueden atraer algunas especies de fauna.",Llorer,2,Laurel
2,840,Acer negundo,"A deciduous tree with a round, irregular crown, native to North America. It blossoms in March and April, just before the leaves appear. It has tiny greenish-yellow flowers, grouped in inflorescences. It produces brownish-green samaras that appear at the beginning of autumn and remain on the tree for six months. It should not be pruned. In Barcelona, it is found in squares, parks and gardens. It can present invasive behaviour.",Box elder,"Arbre caducifoli, de capçada arrodonida i irregular, originari de l'Amèrica del Nord. La floració es produeix durant els mesos de març i d'abril, just abans que apareguin les fulles, amb unes flors diminutes, de color groc verdós, agrupades en inflorescències. Els fruits són disàmares de color verd marronós, que apareixen al principi de la tardor i es mantenen durant sis mesos. No li convé la poda. A Barcelona es pot trobar en places i parcs i jardins. Pot presentar un comportament invasor.","Árbol caducifolio, de copa redondeada e irregular, originario de Norteamérica. La floración se produce durante los meses de marzo y abril, justo antes de que aparezcan las hojas, con unas flores diminutas, de color amarillo verdoso, agrupadas en inflorescencias. Los frutos son disámaras de color verde amarronado, que aparecen a principios de otoño y se mantienen durante seis meses. No le conviene la poda. En Barcelona se puede encontrar en plazas y parques y jardines. Puede presentar un comportamiento invasor.",Negundo,3,"Arce negundo, Negundo"
3,970,Broussonetia papyrifera,"This is a deciduous tree with a round crown. It is native to Eastern Asia. It blossoms between April and May, with insignificant grey and cream male flowers and female flowers that measure 2.5 cm. It produces orange-red globular fruit, which appear in the summer. Its bark fibres are used to make high-quality paper. In Barcelona, it is planted as a street tree and also in parks and gardens.",Paper mulberry,"És un arbre caducifoli, de capçada arrodonida. Originari de l'est d'Àsia. Floreix entre l'abril i el maig, amb flors masculines insignificants, de color gris i crema, i flors femenines de 2,5 centímetres. Els fruits, que apareixen a l'estiu, són globosos i de color vermell ataronjat. De les fibres de l'escorça se'n fa paper d'alta qualitat. Es planta a Barcelona com a arbre viari i en parcs i jardins.","Es un árbol caducifolio, de copa redondeada. Originario del este de Asia. Florece entre abril y mayo, con flores masculinas insignificantes, de color gris y crema, y flores femeninas de 2,5 centímetros. Los frutos, que aparecen en verano, son globosos y de color rojo anaranjado. De las fibras de la corteza se obtiene papel de alta calidad. Se planta en Barcelona como árbol viario y en parques y jardines.",Morera del paper,4,Morera del papel
4,4943585,Phymosia umbellata,"A sparsely-branched evergreen shrub, native to Mexico. It has hairy stems and large, deep-green leaves, with a rugose texture and veining on the lower side. It blossoms from spring to autumn, with violet, purple or scarlet flowers that have a white base, arranged in groups of three.",Mexican Bush Mallow,"Arbust perenne, poc ramificat, originari de Mèxic. Les tiges són piloses, i les fulles són grans, de color verd intens, amb textura rugosa i nerviacions al revers. Floreix de primavera a tardor, amb flors agrupades en grups de fins a tres, de color violeta, porpre o escarlata, i amb la base de color blanc.","Arbusto perenne, poco ramificado, originario de México. Los tallos son pilosos, y las hojas son grandes, de color verde intenso, con textura rugosa y nervaduras en el reverso. Florece de primavera a otoño, con flores agrupadas en grupos de hasta tres, de color violeta, púrpura o escarlata, y con la base de color blanco.",Fimòsia,5,Fimosia


* 5. Desa el DataFrame en un fitxer `.csv`.

In [16]:
df_arbres.to_csv('arbres_barcelona.csv', index=False, encoding='utf-8')
print('Fitxer desat: arbres_barcelona.csv')

Fitxer desat: arbres_barcelona.csv