<h1 style="color: fuchsia;">Nivell 1</h1>

<div style="color: white;">

Importa com un DataFrame l'arxiu `sprint10.xlsx`. Assegura't que el fitxer s'importa correctament, amb els noms de columnes que li corresponen, sense manipular l'arxiu original.

Ordena el DataFrame pel país d'origen. En cas d'empat, ordena pel nom de la ciutat.

Mostra les primeres 10 files.

Addicionalment, fes un `print` on comprovi que el DNI només té valors únics.

</div>

In [1]:
import pandas as pd

df = pd.read_excel("sprint10.xlsx", header= 3, index_col= 0)

print("\nColumnes del DF:")
print(list(df.columns))
print("\nDimensió del DF:")
print(df.shape)

df_ordenat = df.sort_values(
    by= ["País d'origen", "Ciutat"], 
    ascending= True)


print("\nEl camp DNI només conté valors únics:", df["DNI"].is_unique)

print("\nDF ordenat per País d'origen i Ciutat, primeres 10 files")

display(df_ordenat.head(10))

Columnes del DF:
['Nom', 'Cognoms', 'DNI', "País d'origen", 'Ciutat', 'Dia de Naixement', 'Mes de Naixement', 'Any de Naixement', 'Gènere', 'Salari mensual', 'Fills', 'No Fills', 'Grup Professional']

Dimensió del DF:
(1000, 13)

El camp DNI només conté valors únics: True

DF ordenat per País d'origen i Ciutat, primeres 10 files

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
21,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A
154,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B
224,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B
278,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B
602,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D
871,Lea,Fischer,14773153R,Alemanya,Berlín,9,9,1986,D,1.370 €,1.0,NaN,Grup A
281,Lea,Müller,23266650S,Alemanya,Hamburg,14,4,2003,D,1.314 €,NaN,1.0,Grup A
435,Anna,Müller,83274277X,Alemanya,Hamburg,1,1,1987,D,2.464 €,NaN,1.0,Grup C
444,Laura,Schmidt Müller,60161784X,Alemanya,Hamburg,15,6,1987,NC,2.035 €,1.0,NaN,Grup C
487,Lukas,Müller Fischer,60982309S,Alemanya,Hamburg,28,3,1971,H,2.042 €,NaN,1.0,Grup B

<div style="color: white;">

Crea una columna que sigui el nom complet.

Crea una columna si la persona és nascuda a Espanya o no.

Posa el DNI com a índex del DataFrame, és a dir, com a noms de files.

Substitueix el nom de les columnes `Dia de Naixement`, `Mes de Naixement` i `Any de Naixement` per `Dia`, `Mes` i `Any`.

Substitueix `H` per `Home`, `D` per `Dona`, `A` per `Altres` i `NC` per una dada faltant: `NaN`, `NULL` o `NA`.

Mostra tots els canvis que has realitzat en una sola taula.

</div>

In [2]:
df["Nom complet"] = df["Nom"] + " " + df["Cognoms"]

columna = df.pop("Nom complet")
df.insert(0, "Nom complet", columna)

df["Nascuda a Espanya"] = df["País d\'origen"] == "Espanya"

if "DNI" in df.columns:
    df = df.set_index("DNI")

df = df.rename(
    columns={
        "Dia de Naixement": "Dia",
        "Mes de Naixement": "Mes",
        "Any de Naixement": "Any"
    }
)

df["Gènere"] = df["Gènere"].replace(
    {
        "H": "Home",
        "D": "Dona",
        "A": "Altres",
        "NC": pd.NA
    }
)
display(df.head(15))

,Nom complet,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nascuda a Espanya
DNI,,,,,,,,,,,,,,
16928694K,Inês Ferreira Silva,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Dona,1.144 €,NaN,1.0,Grup B,False
27724652S,Clara Sánchez Martínez,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Dona,1.253 €,1.0,NaN,Grup A,True
38141675A,Fatima Fassi,Fatima,Fassi,Marroc,Rabat,6,11,2005,Altres,1.441 €,1.0,NaN,Grup A,False
59157262R,Khadija Bennani Bennani,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Dona,1.944 €,NaN,1.0,Grup B,False
69630528M,Toni Sánchez García,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Home,1.043 €,NaN,1.0,Grup A,True
26930927E,Laia Castells Ferrer,Laia,Castells Ferrer,Espanya,Madrid,16,12,1953,Altres,2.611 €,NaN,1.0,Grup D,True
78247593G,Carla García,Carla,García,Espanya,València,24,12,1957,Dona,942 €,NaN,1.0,Grup A,True
21774231J,Marco Rossi,Marco,Rossi,Itàlia,Torí,3,11,2002,Altres,1.494 €,NaN,1.0,Grup A,False
87316866D,Alessia Rossi,Alessia,Rossi,Itàlia,Milà,6,12,1989,Dona,1.366 €,NaN,1.0,Grup A,False
14219925Z,Toni Martínez,Toni,Martínez,Espanya,Barcelona,16,5,1964,Home,891 €,NaN,1.0,Grup A,True
40695825B,Oriol Sánchez,Oriol,Sánchez,Espanya,Barcelona,27,7,1965,Home,1.250 €,NaN,1.0,Grup A,True
96880751H,Marta Martínez Martínez,Marta,Martínez Martínez,Espanya,Bilbao,23,8,1995,<NA>,2.007 €,NaN,1.0,Grup C,True
66129686T,Jean Dubois,Jean,Dubois,França,Marsella,16,12,1964,Home,1.593 €,1.0,NaN,Grup A,False
74222289K,Toni Castells Romero,Toni,Castells Romero,Espanya,Barcelona,13,4,1961,Home,1.438 €,NaN,1.0,Grup B,True
83982081H,Eva Castells,Eva,Castells,Espanya,Sevilla,3,5,1968,<NA>,1.247 €,1.0,NaN,Grup A,True

<div style="color: white;">

Junta les columnes `Fills` i `No Fills` en una sola columna, utilitzant el mètode `.apply()` i definint una funció que resolgui el problema.

La columna nova ha de dir-se `Fills` i prendre els valors `Sí` o `No`.

</div>

In [3]:
def classificar_fills(fila):
    if pd.notna(fila["Fills"]):
        return "Si"
    elif pd.notna(fila["No Fills"]):
        return "No"
    else:
        return pd.NA

df["Fills"] = df.apply(classificar_fills, axis=1)

df = df.drop(columns=["No Fills"])

display(df.head(10))

,Nom complet,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,Grup Professional,Nascuda a Espanya
DNI,,,,,,,,,,,,,
16928694K,Inês Ferreira Silva,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Dona,1.144 €,No,Grup B,False
27724652S,Clara Sánchez Martínez,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Dona,1.253 €,Si,Grup A,True
38141675A,Fatima Fassi,Fatima,Fassi,Marroc,Rabat,6,11,2005,Altres,1.441 €,Si,Grup A,False
59157262R,Khadija Bennani Bennani,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Dona,1.944 €,No,Grup B,False
69630528M,Toni Sánchez García,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Home,1.043 €,No,Grup A,True
26930927E,Laia Castells Ferrer,Laia,Castells Ferrer,Espanya,Madrid,16,12,1953,Altres,2.611 €,No,Grup D,True
78247593G,Carla García,Carla,García,Espanya,València,24,12,1957,Dona,942 €,No,Grup A,True
21774231J,Marco Rossi,Marco,Rossi,Itàlia,Torí,3,11,2002,Altres,1.494 €,No,Grup A,False
87316866D,Alessia Rossi,Alessia,Rossi,Itàlia,Milà,6,12,1989,Dona,1.366 €,No,Grup A,False
14219925Z,Toni Martínez,Toni,Martínez,Espanya,Barcelona,16,5,1964,Home,891 €,No,Grup A,True

<div style="color: white;">

Crea una taula resum que permeti veure el sou mig, medià, mínim i màxim per `Gènere`.

Ordena la taula en funció del sou mig.

</div>

Modifiquem el tipus de dades de la columna Salari Mensual, passem de text a número per poder operar.

In [4]:
df.select_dtypes(include="number")

df["Salari mensual"] = (
    df["Salari mensual"]
    .astype(str)
    .str.replace("€", "", regex=False)
    .str.replace(".", "", regex=False)
    .str.replace(",", ".", regex=False)
    .str.strip()
)

df["Salari mensual"] = pd.to_numeric(df["Salari mensual"], errors="coerce")

df = df.rename(columns={"Salari mensual": "Salari mensual €"})

In [5]:
display(df)

,Nom complet,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual €,Fills,Grup Professional,Nascuda a Espanya
DNI,,,,,,,,,,,,,
16928694K,Inês Ferreira Silva,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Dona,1144,No,Grup B,False
27724652S,Clara Sánchez Martínez,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Dona,1253,Si,Grup A,True
38141675A,Fatima Fassi,Fatima,Fassi,Marroc,Rabat,6,11,2005,Altres,1441,Si,Grup A,False
59157262R,Khadija Bennani Bennani,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Dona,1944,No,Grup B,False
69630528M,Toni Sánchez García,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Home,1043,No,Grup A,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25161375F,Marta Ferrer Ferrer,Marta,Ferrer Ferrer,Espanya,Sevilla,1,6,1951,Dona,1216,No,Grup B,True
52145541P,Joan García,Joan,García,Espanya,Sevilla,11,4,1959,Home,971,No,Grup A,True
69760120X,Laia Ferrer Martínez,Laia,Ferrer Martínez,Espanya,Barcelona,11,11,1980,Dona,682,No,Grup A,True
82947791W,Jordi García,Jordi,García,Espanya,Barcelona,23,5,1984,Home,1699,Si,Grup C,True
89253307W,Clara Sánchez López,Clara,Sánchez López,Espanya,Bilbao,1,8,1952,Dona,1217,No,Grup A,True

Ara podem crear la taula resum amb el sous per gènere

In [6]:
taula_resum = df.groupby("Gènere")["Salari mensual €"].agg(
    sou_mig="mean",
    sou_medià="median",
    sou_mínim="min",
    sou_màxim="max"
)

taula_resum = taula_resum.sort_values(
    by="sou_mig",
    ascending=False
).round(2)

display(taula_resum)

        sou_mig  sou_medià  sou_mínim  sou_màxim
Gènere
Home    1643.25     1531.0        737       3356
Altres  1626.59     1545.0        703       3175
Dona    1469.44     1361.5        665       3021

<div style="color: white;">

Crea una taula resum amb el salari mig per `Gènere` com a files i `País d'origen` com a columnes.

Afegeix-hi les mitjanes als marges de la taula.

**Extra:** aplica format condicional a la taula per veure amb un color més intens els valors més elevats.

</div>

In [7]:
taula_salari = pd.pivot_table(
    df,
    values="Salari mensual €",
    index="Gènere",
    columns="País d'origen",
    aggfunc="mean",
    margins=True,
    margins_name="Mitjana total"
)

columnes_ordenades = (
    taula_salari
    .loc["Mitjana total"]
    .drop("Mitjana total")
    .sort_values(ascending=False)
    .index
    .tolist()
)

columnes_ordenades.append("Mitjana total")

taula_salari = taula_salari[columnes_ordenades]

display(
    taula_salari
    .style
    .background_gradient(
        cmap="Greens",
        subset=pd.IndexSlice[
            taula_salari.index.drop("Mitjana total"),
            taula_salari.columns.drop("Mitjana total")
        ]
    )
    .format("{:.0f} €", na_rep="-")
)

<div style="color: white;">

Crea una columna nova que sigui la data de naixement en format `Datetime` a partir de les columnes `Dia`, `Mes` i `Any`.

Utilitzant aquesta columna, crea una funció que, donada una data, calculi l'edat actual a dia d'avui.

Utilitza la funció que acabes de crear per generar una columna nova al DataFrame amb l'edat actual.

</div>

In [8]:
df["Data naixement"] = pd.to_datetime(
    dict(
        year=df["Any"],
        month=df["Mes"],
        day=df["Dia"]
    ),
    errors="coerce"
)

df = df.drop(columns=["Dia", "Mes", "Any"])

columna_data = df.pop("Data naixement")
df.insert(6, "Data naixement", columna_data)

In [9]:
def calcular_edat(data_naixement):
    
    if pd.isna(data_naixement):
        return pd.NA
    
    avui = pd.Timestamp.today()
    
    edat = avui.year - data_naixement.year
    
    if (avui.month, avui.day) < (data_naixement.month, data_naixement.day):
        edat -= 1
    
    return edat

df["Edat actual"] = df["Data naixement"].apply(calcular_edat)

columna_edat = df.pop("Edat actual")
df.insert(7, "Edat actual", columna_edat)

display(df)

,Nom complet,Nom,Cognoms,País d'origen,Ciutat,Gènere,Data naixement,Edat actual,Salari mensual €,Fills,Grup Professional,Nascuda a Espanya
DNI,,,,,,,,,,,,
16928694K,Inês Ferreira Silva,Inês,Ferreira Silva,Portugal,Lisboa,Dona,1953-02-25,73,1144,No,Grup B,False
27724652S,Clara Sánchez Martínez,Clara,Sánchez Martínez,Espanya,Barcelona,Dona,1996-03-18,30,1253,Si,Grup A,True
38141675A,Fatima Fassi,Fatima,Fassi,Marroc,Rabat,Altres,2005-11-06,20,1441,Si,Grup A,False
59157262R,Khadija Bennani Bennani,Khadija,Bennani Bennani,Marroc,Rabat,Dona,1995-01-20,31,1944,No,Grup B,False
69630528M,Toni Sánchez García,Toni,Sánchez García,Espanya,Barcelona,Home,1999-08-09,26,1043,No,Grup A,True
...,...,...,...,...,...,...,...,...,...,...,...,...
25161375F,Marta Ferrer Ferrer,Marta,Ferrer Ferrer,Espanya,Sevilla,Dona,1951-06-01,75,1216,No,Grup B,True
52145541P,Joan García,Joan,García,Espanya,Sevilla,Home,1959-04-11,67,971,No,Grup A,True
69760120X,Laia Ferrer Martínez,Laia,Ferrer Martínez,Espanya,Barcelona,Dona,1980-11-11,45,682,No,Grup A,True
82947791W,Jordi García,Jordi,García,Espanya,Barcelona,Home,1984-05-23,42,1699,Si,Grup C,True
89253307W,Clara Sánchez López,Clara,Sánchez López,Espanya,Bilbao,Dona,1952-08-01,73,1217,No,Grup A,True

<h1 style="color: fuchsia;">Nivell 2</h1>

<div style="color: white;">

Utilitzant el següent DataFrame, adjunta la columna `Increment` al DataFrame del nivell anterior.

Actualitza la columna `Salari` en funció dels percentatges que s'adjunten.

No modifiquis manualment els increments: escriu codi Python per fer les conversions necessàries.

</div>

In [10]:
df_increment = pd.DataFrame({
    "Grup": ["Grup A", "Grup B", "Grup C", "Grup D"],
    "Increment": ["5%", "3,5%", "2%", "8%"]
})

display(df_increment)

     Grup Increment
0  Grup A        5%
1  Grup B      3,5%
2  Grup C        2%
3  Grup D        8%

In [11]:
df["Grup Professional"] = df["Grup Professional"].str.strip()
df_increment["Grup"] = df_increment["Grup"].str.strip()

mapa_increments = df_increment.set_index("Grup")["Increment"]

df["Increment"] = df["Grup Professional"].map(mapa_increments)

columna_increment = df.pop("Increment")
df.insert(11, "Increment", columna_increment)

display(df)

,Nom complet,Nom,Cognoms,País d'origen,Ciutat,Gènere,Data naixement,Edat actual,Salari mensual €,Fills,Grup Professional,Increment,Nascuda a Espanya
DNI,,,,,,,,,,,,,
16928694K,Inês Ferreira Silva,Inês,Ferreira Silva,Portugal,Lisboa,Dona,1953-02-25,73,1144,No,Grup B,"3,5%",False
27724652S,Clara Sánchez Martínez,Clara,Sánchez Martínez,Espanya,Barcelona,Dona,1996-03-18,30,1253,Si,Grup A,5%,True
38141675A,Fatima Fassi,Fatima,Fassi,Marroc,Rabat,Altres,2005-11-06,20,1441,Si,Grup A,5%,False
59157262R,Khadija Bennani Bennani,Khadija,Bennani Bennani,Marroc,Rabat,Dona,1995-01-20,31,1944,No,Grup B,"3,5%",False
69630528M,Toni Sánchez García,Toni,Sánchez García,Espanya,Barcelona,Home,1999-08-09,26,1043,No,Grup A,5%,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25161375F,Marta Ferrer Ferrer,Marta,Ferrer Ferrer,Espanya,Sevilla,Dona,1951-06-01,75,1216,No,Grup B,"3,5%",True
52145541P,Joan García,Joan,García,Espanya,Sevilla,Home,1959-04-11,67,971,No,Grup A,5%,True
69760120X,Laia Ferrer Martínez,Laia,Ferrer Martínez,Espanya,Barcelona,Dona,1980-11-11,45,682,No,Grup A,5%,True
82947791W,Jordi García,Jordi,García,Espanya,Barcelona,Home,1984-05-23,42,1699,Si,Grup C,2%,True
89253307W,Clara Sánchez López,Clara,Sánchez López,Espanya,Bilbao,Dona,1952-08-01,73,1217,No,Grup A,5%,True

In [12]:
def convertir_percentatge(valor):
    valor = valor.replace("%", "")
    valor = valor.replace(",", ".")
    valor = float(valor) / 100
    return valor

df["Increment decimal"] = df["Increment"].apply(convertir_percentatge)

df["Salari mensual €"] = (df["Salari mensual €"] * (1 + df["Increment decimal"])).round(2)

display(df)

,Nom complet,Nom,Cognoms,País d'origen,Ciutat,Gènere,Data naixement,Edat actual,Salari mensual €,Fills,Grup Professional,Increment,Nascuda a Espanya,Increment decimal
DNI,,,,,,,,,,,,,,
16928694K,Inês Ferreira Silva,Inês,Ferreira Silva,Portugal,Lisboa,Dona,1953-02-25,73,1184.04,No,Grup B,"3,5%",False,0.035
27724652S,Clara Sánchez Martínez,Clara,Sánchez Martínez,Espanya,Barcelona,Dona,1996-03-18,30,1315.65,Si,Grup A,5%,True,0.050
38141675A,Fatima Fassi,Fatima,Fassi,Marroc,Rabat,Altres,2005-11-06,20,1513.05,Si,Grup A,5%,False,0.050
59157262R,Khadija Bennani Bennani,Khadija,Bennani Bennani,Marroc,Rabat,Dona,1995-01-20,31,2012.04,No,Grup B,"3,5%",False,0.035
69630528M,Toni Sánchez García,Toni,Sánchez García,Espanya,Barcelona,Home,1999-08-09,26,1095.15,No,Grup A,5%,True,0.050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25161375F,Marta Ferrer Ferrer,Marta,Ferrer Ferrer,Espanya,Sevilla,Dona,1951-06-01,75,1258.56,No,Grup B,"3,5%",True,0.035
52145541P,Joan García,Joan,García,Espanya,Sevilla,Home,1959-04-11,67,1019.55,No,Grup A,5%,True,0.050
69760120X,Laia Ferrer Martínez,Laia,Ferrer Martínez,Espanya,Barcelona,Dona,1980-11-11,45,716.10,No,Grup A,5%,True,0.050
82947791W,Jordi García,Jordi,García,Espanya,Barcelona,Home,1984-05-23,42,1732.98,Si,Grup C,2%,True,0.020
89253307W,Clara Sánchez López,Clara,Sánchez López,Espanya,Bilbao,Dona,1952-08-01,73,1277.85,No,Grup A,5%,True,0.050

<div style="color: white;">

Utilitzant un bucle, exporta en 4 fitxers, en format `.xlsx` o `.csv`, les dades de cada `Grup Professional`.

Per exemple:

- `dades_GrupA.xlsx`
- `dades_GrupB.xlsx`
- `dades_GrupC.xlsx`
- `dades_GrupD.xlsx`

Exporta un 5è DataFrame, en format `.xlsx` o `.csv`, que contingui:

- quants treballadors hi ha per cada `Grup Professional`;
- quin és el seu sou mig;
- quina és la seva edat mediana.

</div>

In [13]:
from pathlib import Path

carpeta_sortida = Path("exportacions_grups")
carpeta_sortida.mkdir(exist_ok=True)

for grup, df_grup in df.groupby("Grup Professional"):
    
    nom_grup = grup.replace(" ", "")

    nom_fitxer = f"dades_{nom_grup}.xlsx"
    
    df_grup.to_excel(carpeta_sortida / nom_fitxer, index=True)

In [14]:
resum_grups = (
    df.groupby("Grup Professional")
    .agg(
        Treballadors=("Grup Professional", "count"),
        Sou_mig=("Salari mensual €", "mean"),
        Edat_mediana=("Edat actual", "median")
))

resum_grups["Sou_mig"] = resum_grups["Sou_mig"].round(2)
resum_grups["Edat_mediana"] = resum_grups["Edat_mediana"].round(0).astype(int)


display(resum_grups)

resum_grups.to_excel(carpeta_sortida / "resum_grups.xlsx", index=True)

                   Treballadors  Sou_mig  Edat_mediana
Grup Professional
Grup A                      490  1213.32            51
Grup B                      318  1724.55            48
Grup C                      137  2289.19            52
Grup D                       55  3100.82            44